version: '2'
services:
  zentaos:
    image: registry.saas.hand-china.com/rdchip/zentaopms
    ports:
    - "80:80"
    - "443:443"
    tty: true
    links:
    - mysql:mysql
    volumes:
    - /zentaotmp/data/:/app/src/public/zentaopms/www/data
    # - /zentaotmp/config/:/etc/nginx
    - /jason/nginx/:/etc/nginx/site-enabled
  mysql:
    image: mysql:5.7
    ports:
    - "3306:3306"
    tty: true
    environment:
     MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
    - /zentaotmp/mysql/:/var/lib/mysql
