version: '2'
services:
  zentaos:
    image: registry.saas.hand-china.com/rdchip/zentaopms
    ports:
    - "8080:80"
    - "443:443"
    # tty: true
    volumes:
    - /mnt/docker/rdc/www/data:/app/src/public/zentaopms/www/data
    - /mnt/docker/rdc/tmp/backup:/app/src/public/zentaopms/tmp/backup
    - /mnt/docker/rdc/tmp/log:/app/src/public/zentaopms/tmp/log
    - /mnt/docker/rdc/module/hdc/data:/app/src/public/zentaopms/module/hdc/data
    - /mnt/docker/rdc/module/bulletin/data:/app/src/public/zentaopms/module/bulletin/data
    - /mnt/docker/rdc/config:/app/src/public/zentaopms/config
